#!/bin/bash
### BEGIN INIT INFO
# Provides:          print-monitor
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Prints PDF files
# Description:       Monitors folder for added files and prints them
### END INIT INFO

if [ -f /etc/print-monitor.conf ]; then source /etc/print-monitor.conf
elif echo "ERROR: Please move the config file to /etc/print-monitor.conf"; then exit
fi

inotifywait -m -e close_write --format '%w%f' "$monitorDir" | while read file;
do
	lpr -P "$printerQueue" "${file}";
	sudo rm -f "${file}";
done
