#!/bin/sh
### BEGIN INIT INFO
# Provides:          print-monitor
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Prints PDF files
# Description:       Monitors folder for added files and prints them
### END INIT INFO

MONITORDIR="/home/pi/ftp/invoice/"
inotifywait -m -e close_write --format '%w%f' "${MONITORDIR}" | while read file;
do
	lpr -P TSP650II  "${file}";
	sudo rm -f "${file}";
done
